[[snippets]]
  description = "find file by exact name"
  command = "find ./ -name <file-name>"
  tag = ["find", "files"]
  output = ""

[[snippets]]
  description = "find files open by a process"
  command = "lsof -f <pid>"
  tag = ["files", "process"]
  output = ""

[[snippets]]
  description = "mitmproxy - proxy traffic to a directory"
  command = "mitmproxy --listen-port <listen-port> --map-local='|~m GET|<proxy-from>|<to-dir-or-file>'"
  tag = ["mitmproxy"]
  output = ""

[[snippets]]
  description = "mitmproxy - listen traffic"
  command = "mitmproxy --mode reverse:<addr> -p <listen-on-port>"
  tag = ["mitmproxy"]
  output = ""

[[snippets]]
  description = "find process listenning on port"
  command = "sudo netstat -tunlp | grep \":<port>\""
  tag = ["network"]
  output = ""

[[snippets]]
  description = "check weather"
  command = "curl wttr.in/<city>"
  tag = ["weather"]
  output = ""

[[snippets]]
  description = "python - create virtual environment"
  command = "pyenv virtualenv <python-version> <project-name>"
  tag = ["python", "pyenv"]
  output = ""

[[snippets]]
  description = "python - activate virtual environment"
  command = "pyenv activate <project-name>"
  tag = ["python", "pyenv"]
  output = ""

[[snippets]]
  description = "Show docker disk usage"
  command = "docker system df"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Remove unusek docker images"
  command = "docker image prune"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "copy local file to the docker container"
  command = "docker cp <source_file> <container_name>:<destination>"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Copy local file to a running image by docker compose"
  command = "docker compose cp <source_file> <container_name>:<destination>"
  tag = ["docker-compose"]
  output = ""
